baseURL: 'https://ckaserer.dev/test/'
canonifyURLs: true # only required for suddir in baseURL
languageCode: 'en-us'

title: "ckaserer.dev"
theme: "toha"

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/ckaserer/test

  footer:
    enable: false