import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  skyledgerSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Skyledger Overview',
    },
    {
      type: 'category',
      label: 'Architecture Decision Records (ADRs)',
      link: { type: 'doc', id: 'adr/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
  ],
};

export default sidebars;
