import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   personalOsSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars: SidebarsConfig = {
personalOsSidebar: [
            {
              type: 'doc',
              id: 'MyPersonalOS',
              label: 'My Personal OS',
            },
            // {
            //   type: 'category',
            //   label: 'Finanzen',
            //   items: [
            //     { type: 'autogenerated', dirName: 'finance' },
            //   ],
            // },
            {
              type: 'category',
              label: 'Decision Making',
              items: [
                { type: 'autogenerated', dirName: 'decision-making' },
              ],
            }
  ],
};

export default sidebars;

